application: application-id-of-your-own
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static/(.*)
  static_files: static/\1
  upload: static/(.*)

- url: /_ah/login_required
  script: main.app

- url: .*
  script: main.app
